### PR TITLE
CLI Parsing Review and Fixes

### LINKED ISSUE #137: Tools usage is broken for conventional syntax
While reviewing doc changes for #133, I noticed that -Tcljwatson usage is somewhat broken.

For example, the README suggests:
```
clojure -Tclj-watson scan :deps-edn-path '"deps.edn"' :output '"stdout"'
# or:
clojure -Tclj-watson scan '{:deps-edn-path "deps.edn" :output "stdout"}'
``` 

Both these variants result in:
```
* ERROR: Invalid value for argument: Specified file not found
  :p, :deps-edn-path <file> Path of deps.edn file to scan [*required*]
```

But these work fine:
```
clojure -Tclj-watson scan :deps-edn-path deps.edn :output stdout
# or:
clojure -Tclj-watson scan '{:deps-edn-path deps.edn :output stdout}'
```

I don't typically use clojure tools because I find the command-line syntax too finicky for me.

That said, I'm the one who broke this a while back, so I shall fix it.
The coercion I applied means we can specify `deps.edn` instead of the conventional syntax of `'"deps.edn"'`, but I also seem to have broken the conventional syntax.

### PR DESCRIPTION
**Pull request by lread**
For example, `:p '"deps.edn"'` is now accepted.

Closes #137

### CODE REVIEW

**Comment by lread** [comment]
Ok, sounds good. I will convert this PR to draft for now and see what I can come up with.

**Comment by lread** [comment]
Ok, I think that was worthwhile @seancorfield.
The exercise resulted in me finding and fixing a few things (please see commit msgs for details).

File: src/clj_watson/entrypoint.clj [hunk 1]
```diff
@@ -46,23 +46,36 @@
...
+      opts
+      (do-scan opts))))
 
 #_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}
 (defn scan
   "Direct entrypoint for -X & -T usage."
   [opts]
-  (do-scan (cli-spec/validate-tool-opts opts)))
+  (let [{:keys [exit]} (scan-exec opts)]
+    (System/exit exit)))
```
Comment (seancorfield) [inline src/clj_watson/entrypoint.clj:78]: -X/-T should never call System/exit. Only -M should do that.

-X/-T should throw an exception if they fail.

Comment (lread) [reply src/clj_watson/entrypoint.clj]: Okey dokey, done!

I wish there were something better clojure -X/-T could do with regards to error handling. To me, it seems user-confusing to throw and present an exception on, for example, a cli usage error. Oh well.

Lemme know if you find anything else.

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,15 @@
...
 * v6.1.0 in progress
   * Fix references to `clj-watson.properties` file in the documentation via PR [#130](https://github.com/clj-holmes/clj-watson/pull/130) from [@samumbach](https://github.com/samumbach).
+  * Command line parsing review and fixes [#137](https://github.com/clj-holmes/clj-watson/issues/137)
+    * -X/-T exec usage, as per convention, now throws on error instead of explicitly exiting process
+    * -X/-T exec usage now allows for conventional value syntax, e.g. `:p '"deps.edn"'` now works (in addition to `:p deps.edn`). 
+    * -X/-T exec usage invalid boolean values now trigger an error (instead of being ignored)
+    * now warning when using `dependency-check`-only options with `github-advisory` `database-strategy`
+    * now reporting unrecognized options in appropriate style for -M vs -X/-T usage
+    * command line usage errors reviewed and updated for succinctness and clarity
+    * made code more REPL friendly by only issuing System/exit add out edges of API
```
Comment (seancorfield) [inline CHANGELOG.md:12]: I'm not sure how to read this... "add out edges"?

Comment (lread) [reply CHANGELOG.md:12]: I, Sean, am the king of typos. Thanks for catching that one!
